# Generated by Django 4.2.4 on 2023-08-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_rename_image_bookmark_image_file_bookmark_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
