# Generated by Django 4.2.4 on 2023-08-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_alter_bookmark_title_alter_collection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='collection',
        ),
        migrations.CreateModel(
            name='BookmarksCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.bookmark')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.collection')),
            ],
        ),
        migrations.AddField(
            model_name='bookmark',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, through='bookmarks.BookmarksCollections', to='bookmarks.collection'),
        ),
    ]
