# Generated by Django 4.2.4 on 2023-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_remove_bookmark_collection_bookmarkscollections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmarks', through='bookmarks.BookmarksCollections', to='bookmarks.collection'),
        ),
    ]
