# Generated by Django 4.2.4 on 2023-08-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0011_alter_bookmark_collections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-last_update'], 'verbose_name': 'Bookmark', 'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='type_of_link',
            field=models.CharField(choices=[('website', 'website'), ('book', 'book'), ('article', 'article'), ('music', 'music'), ('video', 'video')], default='website', null=True, verbose_name='type'),
        ),
    ]
