# Generated by Django 4.2.4 on 2023-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0013_alter_bookmark_type_of_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
